services:
  authapi:
    build: ./auth
    ports:
      - "9000:9000"
    networks:
      - social-network

  socialapi:
    build: ./social
    ports:
      - "3500:3500"
    depends_on:
      - authapi
    networks:
      - social-network

networks:
  social-network:
    driver: bridge
